{
	{
		Groups = {
			"GStash",
		},
		LootTableIds = {
			"Drop_12gauge_Buckshot",
		},
		handle = 485007360,
		map = "QcNU7NV",
		name = 'IntelInventoryItemSpawn#360 "SECRET STASH" (GStash)',
		path = "IntelInventoryItemSpawn ",
		type = "IntelInventoryItemSpawn",
	},
	{
		Groups = {
			"LegionTalk",
		},
		handle = 1008553941,
		items = {
			{
				editor_view_abridged = "Start conversation.",
				filter_type = "conversation",
				reference_id = "GCExLegionTalk",
				type = "UnitStartConversation",
			},
		},
		map = "QcNU7NV",
		name = "Logic#941 (LegionTalk)",
		path = "Logic ",
		type = "Logic",
	},
	{
		Groups = {
			"LegionScouts",
			"LegionScoutsSirNi",
		},
		handle = 1111408254,
		items = {},
		map = "QcNU7NV",
		name = "UnitMarker#254 (LegionScouts, LegionScoutsSirNi)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionScouts",
			"LegionScoutsSirNi",
		},
		handle = 1248793159,
		items = {},
		map = "QcNU7NV",
		name = "UnitMarker#159 (LegionScouts, LegionScoutsSirNi)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionScouts",
			"LegionScoutsPhill",
		},
		handle = 1249303736,
		items = {},
		map = "QcNU7NV",
		name = "UnitMarker#736 (LegionScouts, LegionScoutsPhill)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionScouts",
		},
		handle = 1304221840,
		items = {},
		map = "QcNU7NV",
		name = "UnitMarker#840 (LegionScouts)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionScouts",
			"LegionScoutsPhill",
		},
		handle = 1321335333,
		items = {},
		map = "QcNU7NV",
		name = "UnitMarker#333 (LegionScouts, LegionScoutsPhill)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"GStash",
		},
		handle = 1387273542,
		items = {
			{
				editor_view_abridged = "LootedStash5 = true",
				filter_type = "quest",
				reference_id = "GearUp",
				type = "QuestSetVariableBool",
				var = "LootedStash5",
			},
		},
		map = "QcNU7NV",
		name = "Logic#542 (GStash)",
		path = "Logic ",
		type = "Logic",
	},
	{
		Groups = {
			"LegionScouts",
		},
		handle = 1432511448,
		items = {},
		map = "QcNU7NV",
		name = "UnitMarker#448 (LegionScouts)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionScouts",
			"LegionScoutsSirNi",
		},
		handle = 1435153316,
		items = {},
		map = "QcNU7NV",
		name = "UnitMarker#316 (LegionScouts, LegionScoutsSirNi)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionScouts",
		},
		handle = 1557817747,
		items = {},
		map = "QcNU7NV",
		name = "UnitMarker#747 (LegionScouts)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionScouts",
		},
		handle = 1648533262,
		items = {},
		map = "QcNU7NV",
		name = "UnitMarker#262 (LegionScouts)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionScouts",
		},
		handle = 1658991385,
		items = {},
		map = "QcNU7NV",
		name = "UnitMarker#385 (LegionScouts)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionScouts",
		},
		handle = 1700548736,
		items = {},
		map = "QcNU7NV",
		name = "UnitMarker#736 (LegionScouts)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionScouts",
		},
		handle = 1724842949,
		items = {},
		map = "QcNU7NV",
		name = "UnitMarker#949 (LegionScouts)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionScouts",
			"LegionScoutsPhill",
		},
		handle = 1830048647,
		items = {},
		map = "QcNU7NV",
		name = "UnitMarker#647 (LegionScouts, LegionScoutsPhill)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
}