{
	{
		Groups = {
			"LegionSquad",
			"KillCougar",
		},
		handle = 1022934600,
		items = {},
		map = "cKFSRpQ",
		name = "UnitMarker#600 (LegionSquad, KillCougar)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"MERCSquad",
		},
		handle = 1263826464,
		items = {},
		map = "cKFSRpQ",
		name = "UnitMarker#464 (MERCSquad)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionSquad",
		},
		handle = 1373002377,
		items = {},
		map = "cKFSRpQ",
		name = "UnitMarker#377 (LegionSquad)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"MERCSquad",
		},
		handle = 1387631142,
		items = {},
		map = "cKFSRpQ",
		name = "UnitMarker#142 (MERCSquad)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionSquad",
			"KillStogie",
		},
		handle = 1399498435,
		items = {},
		map = "cKFSRpQ",
		name = "UnitMarker#435 (LegionSquad, KillStogie)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionSquad",
			"KillGaston",
		},
		handle = 1436298537,
		items = {},
		map = "cKFSRpQ",
		name = "UnitMarker#537 (LegionSquad, KillGaston)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionSquad",
			"KillNumb",
		},
		handle = 1521867924,
		items = {},
		map = "cKFSRpQ",
		name = "UnitMarker#924 (LegionSquad, KillNumb)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionSquad",
			"KillCougar",
		},
		handle = 1522036715,
		items = {},
		map = "cKFSRpQ",
		name = "UnitMarker#715 (LegionSquad, KillCougar)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"MERCSquad",
		},
		handle = 1613172225,
		items = {},
		map = "cKFSRpQ",
		name = "UnitMarker#225 (MERCSquad)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"MERCSquad",
		},
		handle = 1618771597,
		items = {},
		map = "cKFSRpQ",
		name = "UnitMarker#597 (MERCSquad)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionSquad",
			"KillGaston",
		},
		handle = 1634111768,
		items = {},
		map = "cKFSRpQ",
		name = "UnitMarker#768 (LegionSquad, KillGaston)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionSquad",
			"KillStogie",
		},
		handle = 1682743560,
		items = {},
		map = "cKFSRpQ",
		name = "UnitMarker#560 (LegionSquad, KillStogie)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionSquad",
		},
		handle = 1690510299,
		items = {},
		map = "cKFSRpQ",
		name = "UnitMarker#299 (LegionSquad)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionSquad",
		},
		handle = 1834863124,
		items = {},
		map = "cKFSRpQ",
		name = "UnitMarker#124 (LegionSquad)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionSquad",
		},
		handle = 1874543867,
		items = {},
		map = "cKFSRpQ",
		name = "UnitMarker#867 (LegionSquad)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
	{
		Groups = {
			"LegionSquad",
			"KillNumb",
		},
		handle = 1876375643,
		items = {},
		map = "cKFSRpQ",
		name = "UnitMarker#643 (LegionSquad, KillNumb)",
		path = "UnitMarker ",
		type = "UnitMarker",
	},
}