return PlaceObj('ModDef', {
	'title', "Grand Chien Expanded: Prologue",
	'description', "[h1]Grand Chien Expanded: Prologue[/h1]\n\n[h3]Disclaimer[/h3]\nPlease note that only Ernie Island is fully available right now, we will soon release all the content included in Seagul Island, voicelines and more. Your feedback is very important for future improvements. GG <3\n\n[h3]Read me[/h3]\n- This mod disables the AIM and IMP page, so please disable it if you you play the vanilla campaign.\n- No fast travel is allowed, it is intended\n- You have 6 months in game to finish the campaign\n- There is no militia, no diamond shipments, no Bobby Rays and no enemy squads in the sector, no outposts, no roaming squads\n- For a better experience use only the recommended mods\n\n[h2]About...[/h2]\nThis mod is part of the Grand Chien Expanded Experience, where the players can explore the untold stories of Grand Chien and get to know some of its more colourful characters up close.\n\n[h2]The Story...[/h2]\nThe events of the Prologue transpire prior to the abduction of the president and tells the story of Biff and his M.E.R.C. Squad when first landing on Erny Island. His mission soon became a truly unforgettable experience in Grand Chien...\nAs Player you are reliving what has happened on Erny Island upon to the point of an catastrophic event…\nAre the famous M.E.R.C.‘s getting out of this one alive?\n\n[h2]Content:[/h2]\n-  includes the Maps of Erny from the base game, Erny Village is in a festive mood\n-  new NPCs with dialogues and interactions\n-  known NPCs with new dialogue lines\n-  some of the mercenaries from M.E.R.C. will be playable, like Gaston, Stogie, Numb and more\n- there are Seven! entirely New Sectors added to explore\n- a Backstory connecting to events in the base game\n- difficulty hard, since there are restrictions in place: like no AIM, no fast travel, no Bobby Rays\n- there is also no Economic in place (Team is hired for the duration of the campaign)\n\n\nEnjoy your playthrough and thanks for playing!\n\nThe entire GCExp-Team,\n\n[h3]Modding-Team and Contributors[/h3]\n[b] SirNi[/b] - Idea & Concept, Coding\n[b] coockadoodledoo[/b] - Maps, Story & Dialogues \n[b] Morianthi[/b] - Models, Portraits \n[b] PapillOn[/b] - Dialogue (and Implementation), Quests\nSpecial thanks to: [b]injto4ka[/b] for Technical Support on the Editor\n\n[h3]Further contributors[/h3]\nwhahappen (Loot), A.Rose (Writing Consultant), Lucjan + Rato (Advice), Emperor (Moral Support), Fallout (Tech), Gadina (Advice)\n\n[h3]Thanks to[/h3]\n[b]MyOneGod[/b] - Nocturnal Beauty\n[b]Kira[/b] – Audakis Training Overhaul\n[b]Lucjan[/b] - Audakis Training Overhaul 1.5.1\n[b]SkunkXL + zulib[/b] – all nationalitieslib\n[h3]for letting us use your mods![/h3]\n[i]Thanks to all HG staff for developing JA3 despite all difficulties. Happy Anniversary![/i]\n\n[i]And a very special thanks to NinaApp for incredible entertainment![/i]",
	'image', "Mod/GCExPrologue/Images/Campaign1-Seite001.png",
	'external_links', {
		"https://github.com/yasumitsu/GCExPrologue",
	},
	'last_changes', "-- fixed lot of stuff",
	'id', "GCExPrologue",
	'author', "Sir Ni",
	'version', 1253,
	'lua_revision', 233360,
	'saved_with_revision', 350233,
	'code', {
		"Code/Script.lua",
		"MapPatches/SetPieces/NewSetpiece_pwswuST/GCExLanding.lua",
		"CharacterEffect/Gasket.lua",
		"CharacterEffect/NumbTalk.lua",
		"CharacterEffect/Gaston.lua",
		"CharacterEffect/GumpySpecialPineapple.lua",
		"CharacterEffect/GruntForce.lua",
		"CharacterEffect/ByTheBook.lua",
		"UnitData/GCExBiff.lua",
		"UnitData/GCEXFlo.lua",
		"UnitData/GCEXHaywire.lua",
		"UnitData/GCEXRazor.lua",
		"UnitData/GCEXLarry.lua",
		"UnitData/GCEXSmiley.lua",
		"UnitData/GCExMartha.lua",
		"UnitData/GCExBasil.lua",
		"UnitData/GCExLuc.lua",
		"UnitData/GCExBillyBoy.lua",
		"UnitData/GCExSantiago.lua",
		"UnitData/GCExHerman.lua",
		"UnitData/GCExDeeDee.lua",
		"UnitData/GCExBastien.lua",
		"UnitData/GCExBrian.lua",
		"UnitData/GCExStephane.lua",
		"UnitData/GCExSmurge.lua",
		"UnitData/GCExStitches.lua",
		"UnitData/GCExZombie_F.lua",
		"UnitData/GCExZombie_M.lua",
		"UnitData/GCExAdonisGuard.lua",
		"UnitData/GCExGoon_1.lua",
		"UnitData/GCExGoon_2.lua",
		"UnitData/GCExGoon_3.lua",
		"UnitData/GCExGoon_4.lua",
		"UnitData/GCEXNumb.lua",
		"UnitData/GCEXGumpy.lua",
		"UnitData/GCEXGasket.lua",
		"UnitData/GCEXStogie.lua",
		"UnitData/GCEXCougar.lua",
		"UnitData/GCEXGaston.lua",
		"InventoryItem/WilcoxNotes_1.lua",
	},
	'default_options', {},
	'has_data', true,
	'saved', 1720949818,
	'code_hash', -7573367671379325284,
	'affected_resources', {
		PlaceObj('ModResourcePreset', {
			'Class', "GameDifficultyDef",
			'Id', "Normal",
			'Prop', "display_name",
			'ClassDisplayName', "Game difficulty",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "GameDifficultyDef",
			'Id', "Hard",
			'Prop', "display_name",
			'ClassDisplayName', "Game difficulty",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "GameDifficultyDef",
			'Id', "VeryHard",
			'Prop', "display_name",
			'ClassDisplayName', "Game difficulty",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CampaignPreset",
			'Id', "GCEXPrologue",
			'ClassDisplayName', "Campaign",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "DayTracker",
			'ClassDisplayName', "Quest",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "Emails",
			'ClassDisplayName', "Quest",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "FailedQuests",
			'ClassDisplayName', "Quest",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "MercStateTracker",
			'ClassDisplayName', "Quest",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "PopupTracker",
			'ClassDisplayName', "Quest",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "TimedTrap",
			'ClassDisplayName', "Quest",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "GCEx_01_Landing",
			'ClassDisplayName', "Quest",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "GearUp",
			'ClassDisplayName', "Quest",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "ReadyForRailings",
			'ClassDisplayName', "Quest",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "BriansFuel",
			'ClassDisplayName', "Quest",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "TropicalHeat",
			'ClassDisplayName', "Quest",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "QuestsDef",
			'Id', "ChurchOfBlood",
			'ClassDisplayName', "Quest",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "SetpiecePrg",
			'Id', "GCExLanding",
			'ClassDisplayName', "Setpiece",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Camera",
			'Id', "GCExErnie",
			'ClassDisplayName', "Camera",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "PDAAIMBrowser",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "PDAImpDialog",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "Gasket",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "NumbTalk",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "Gaston",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "GumpySpecialPineapple",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "GruntForce",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "CharacterEffectCompositeDef",
			'Id', "ByTheBook",
			'ClassDisplayName', "Character effect",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "SectorOperation",
			'Id', "GCExProCraftCommonBase",
			'ClassDisplayName', "Sector operation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "SectorOperation",
			'Id', "GCExProCraftAmmo",
			'ClassDisplayName', "Sector operation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "SectorOperation",
			'Id', "GCExProCraftExplosives",
			'ClassDisplayName', "Sector operation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "SectorOperation",
			'Id', "GCExProGatherIntel",
			'ClassDisplayName', "Sector operation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "SectorOperation",
			'Id', "GCExProIdle",
			'ClassDisplayName', "Sector operation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "SectorOperation",
			'Id', "GCExProRandR",
			'ClassDisplayName', "Sector operation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "SectorOperation",
			'Id', "GCExProRepairItems",
			'ClassDisplayName', "Sector operation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "SectorOperation",
			'Id', "GCExProTrainMercs",
			'ClassDisplayName', "Sector operation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "SectorOperation",
			'Id', "GCExProTreatWounds",
			'ClassDisplayName', "Sector operation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "SectorOperation",
			'Id', "GCExProArriving",
			'ClassDisplayName', "Sector operation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "SectorOperation",
			'Id', "GCExProTravelling",
			'ClassDisplayName', "Sector operation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "BrianNPC",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "StephaneNPC",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "SmurgeNPC",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "AdonisGuard1NPC",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "AdonisGuard2NPC",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Zombie1_F",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Zombie2_M",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "BastienPro",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "DeedeePro",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "MarthaPro",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "HermanPro",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Goon1Pro",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Goon2Pro",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Goon3Pro",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Goon4Pro",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "GoonCommander",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Haywire-Appearance",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Numb-Appearance",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Razor-Appearance",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Gumpy-Appearance",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Gasket-Appearance",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Flo-Appearance",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Bubba-Appearance",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Biff-Appearance",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Stogie-Appearance",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Cougar-Appearance",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "Gaston-Appearance",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCExBiff",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCEXFlo",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCEXHaywire",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCEXRazor",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCEXLarry",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCEXSmiley",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCExMartha",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCExBasil",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCExLuc",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCExBillyBoy",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCExSantiago",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCExHerman",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCExDeeDee",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCExBastien",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCExBrian",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCExStephane",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCExSmurge",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCExStitches",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCExZombie_F",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCExZombie_M",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCExAdonisGuard",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCExGoon_1",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCExGoon_2",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCExGoon_3",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCExGoon_4",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCEXNumb",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCEXGumpy",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCEXGasket",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCEXStogie",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCEXCougar",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "GCEXGaston",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "Fuel_2",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "SmurgeZombieEvent",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "QuestCompletionCoB",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "ArrivedAtChurch",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "LeaveSector",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "ChurchQuestStart",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "LandingSeagull",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "LandingSeagull2",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "GCExDeedee",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "GCExStephane",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "GCExMartha",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "GCExBiff",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "GCExBastien",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "GCExBarChat",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "GCExLegionTalk",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Conversation",
			'Id', "GCExThugs",
			'ClassDisplayName', "Conversation",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Erny3",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "BrianChest",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Erny2",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Erny1",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "DayoneSeagull",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "RecentActivity",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Clue5MedFacility",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Playground",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Clue4MedFacility",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Clue3Airport",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Clue2Airport",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "OutlookWaste",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "OutlookGods",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "FirstTimeZombies",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "FuelFound",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "BanterDef",
			'Id', "Colonizer",
			'ClassDisplayName', "Banter",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "InventoryItemCompositeDef",
			'Id', "WilcoxNotes_1",
			'ClassDisplayName', "Inventory item",
		}),
	},
	'steam_id', "3263079596",
	'TagQuest&Campaigns', true,
})