UndefineClass('GCExStogie')
DefineClass.GCExStogie = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",


	NameColor = 4292643868,
	object_class = "UnitData",
	Health = 98,
	Agility = 78,
	Dexterity = 84,
	Strength = 96,
	Wisdom = 77,
	Leadership = 33,
	Marksmanship = 89,
	Mechanical = 74,
	Explosives = 43,
	Medical = 11,
	Portrait = "Mod/GCExPrologue/Images/StogiePortrait",
	BigPortrait = "Mod/GCExPrologue/Images/Stogie",
	IsMercenary = true,
	Name = T(112445946149, --[[ModItemUnitDataCompositeDef GCExStogie Name]] 'Lt. "Stogie" Horge'),
	Nick = T(297085285316, --[[ModItemUnitDataCompositeDef GCExStogie Nick]] "Stogie"),
	AllCapsNick = T(104451916638, --[[ModItemUnitDataCompositeDef GCExStogie AllCapsNick]] "STOGIE"),
	Affiliation = "Secret",
	Bio = T(703872402200, --[[ModItemUnitDataCompositeDef GCExStogie Bio]] "Built like a tank, Lt. Horge's speciality is destroying them. Extremely skilled with heavy weapons, Stogie spent the last two years working as an independent mercenary in the Congo. He's one of the toughest grunts in the business, and M.E.R.C. is proud that he has chosen us as his first foray into agency representation, even if it is on a temporary trial basis.\n\nAdditional Info\nPlease hire Stogie. We don't want to lose him.\" -M.E.R.C. Dossier"),
	Nationality = "USA",
	snype_nick = T(159796160036, --[[ModItemUnitDataCompositeDef GCExStogie snype_nick]] "stogie"),
	Refusals = {},
	Haggles = {},
	Mitigations = {},
	ExtraPartingWords = {},
	Offline = {},
	GreetingAndOffer = {},
	ConversationRestart = {},
	IdleLine = {},
	PartingWords = {},
	RehireIntro = {},
	RehireOutro = {},
	MedicalDeposit = "none",
	StartingSalary = 470,
	SalaryIncrease = 280,
	SalaryLv1 = 100,
	SalaryMaxLv = 4100,
	LegacyNotes = "Built like a tank, Lt. Horge's speciality is destroying them. Extremely skilled with heavy weapons, Stogie spent the last two years working as an independent mercenary in the Congo. He's one of the toughest grunts in the business, and M.E.R.C. is proud that he has chosen us as his first foray into agency representation, even if it is on a temporary trial basis.\n\nAdditional Info\nPlease hire Stogie. We don't want to lose him.\" -M.E.R.C. Dossier",
	StartingLevel = 7,
	MaxHitPoints = 82,
	Likes = {
		"Gus",
	},
	Dislikes = {
		"Meltdown",
	},
	StartingPerks = {
		"GruntForce",
		"HeavyWeaponsTraining",
		"BeefedUp",
		"BreachAndClear",
		"Ironclad",
		"CollateralDamage",
		"HardBlow",
		"HitTheDeck",
	},
	AppearancesList = {
		PlaceObj('AppearanceWeight', {
			'Preset', "Stogie-Appearance",
		}),
	},
	Equipment = {
		"Gus",
	},
	Tier = "Legendary",
	Specialization = "Marksmen",
	gender = "Male",
	blocked_spots = set( "Weaponls", "Weaponrs" ),
	VoiceResponseId = "GCExStogie",
}

