UndefineClass('GCExHaywire')
DefineClass.GCExHaywire = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",


	NameColor = 4282219161,
	object_class = "UnitData",
	Health = 65,
	Agility = 59,
	Dexterity = 76,
	Strength = 71,
	Wisdom = 58,
	Leadership = 1,
	Marksmanship = 48,
	Mechanical = 8,
	Explosives = 31,
	Medical = 2,
	Portrait = "Mod/GCExPrologue/Images/HaywirePortrait",
	BigPortrait = "Mod/GCExPrologue/Images/Haywire",
	Name = T(749871154545, --[[ModItemUnitDataCompositeDef GCExHaywire Name]] 'Frankie "Haywire" Gordon'),
	Nick = T(977562677594, --[[ModItemUnitDataCompositeDef GCExHaywire Nick]] "Haywire"),
	AllCapsNick = T(828404684603, --[[ModItemUnitDataCompositeDef GCExHaywire AllCapsNick]] "HAYWIRE"),
	Affiliation = "Other",
	Bio = T(436581784584, --[[ModItemUnitDataCompositeDef GCExHaywire Bio]] "Killing is Frankie Gordon's speciality. He's not particular on how he kills, just as long as he has fun doing it. Haywire may not be considered a marksman, but he exhibits a certain fascination with automatic weapons and seems to handle them with ease. The same could be said for his talents with sharp knives. Additional info:\n\nFrankie is working on improving his people skills."),
	Nationality = "USA",
	Title = T(440783434649, --[[ModItemUnitDataCompositeDef GCExHaywire Title]] "Wicked"),
	snype_nick = T(881909539454, --[[ModItemUnitDataCompositeDef GCExHaywire snype_nick]] "hay.wire"),
	Refusals = {},
	Haggles = {},
	Mitigations = {},
	ExtraPartingWords = {},
	Offline = {},
	GreetingAndOffer = {},
	ConversationRestart = {},
	IdleLine = {},
	PartingWords = {},
	RehireIntro = {},
	RehireOutro = {},
	MedicalDeposit = "none",
	StartingSalary = 470,
	SalaryIncrease = 280,
	SalaryLv1 = 100,
	SalaryMaxLv = 4100,
	LegacyNotes = '"Killing is Frankie Gordon\'s speciality. He\'s not particular on how he kills, just as long as he has fun doing it. Haywire may not be considered a marksman, but he exhibits a certain fascination with automatic weapons and seems to handle them with ease. The same could be said for his talents with sharp knives. Additional info:\n\nFrankie is working on improving his people skills."\n\n- M.E.R.C. Dossier',
	immortal = true,
	MaxHitPoints = 82,
	Likes = {
		"GCEXRazor",
	},
	StartingPerks = {
		"AutoWeapons",
		"MeleeTraining",
		"Psycho",
	},
	AppearancesList = {
		PlaceObj('AppearanceWeight', {
			'Preset', "Haywire-Appearance",
		}),
	},
	AdditionalGroups = {
		PlaceObj('AdditionalGroup', {
			'Name', "MERC",
		}),
	},
	Specialization = "AllRounder",
	gender = "Male",
	blocked_spots = set( "Weaponls", "Weaponrs" ),
	PersistentSessionId = "GCEXHaywire",
}

