UndefineClass('GCExGasket')
DefineClass.GCExGasket = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",


	NameColor = 4292643868,
	object_class = "UnitData",
	Health = 72,
	Agility = 61,
	Dexterity = 89,
	Strength = 68,
	Wisdom = 49,
	Leadership = 3,
	Marksmanship = 44,
	Mechanical = 82,
	Explosives = 8,
	Medical = 0,
	Portrait = "Mod/GCExPrologue/Images/GasketPortrait",
	BigPortrait = "Mod/GCExPrologue/Images/Gasket",
	IsMercenary = true,
	Name = T(949646749914, --[[ModItemUnitDataCompositeDef GCExGasket Name]] 'Doug "Gasket" Milton'),
	Nick = T(854815094946, --[[ModItemUnitDataCompositeDef GCExGasket Nick]] "Gasket"),
	AllCapsNick = T(801666550540, --[[ModItemUnitDataCompositeDef GCExGasket AllCapsNick]] "GASKET"),
	Affiliation = "Secret",
	Bio = T(242637099594, --[[ModItemUnitDataCompositeDef GCExGasket Bio]] "Doug Milton originates from Kentucky. He quit school in the fourth grade to work in his father's gas station. When his sister/cousin started pumping gas at the garage, he transferred his focus to the repair bench, and became a good mechanic. Since he left the family business, he roamed from job to job before trying his luck as a mercenary."),
	Nationality = "USA",
	snype_nick = T(534857338517, --[[ModItemUnitDataCompositeDef GCExGasket snype_nick]] "doug.milton"),
	Refusals = {},
	Haggles = {},
	Mitigations = {},
	ExtraPartingWords = {},
	Offline = {},
	GreetingAndOffer = {},
	ConversationRestart = {},
	IdleLine = {},
	PartingWords = {},
	RehireIntro = {},
	RehireOutro = {},
	MedicalDeposit = "none",
	StartingSalary = 470,
	SalaryIncrease = 280,
	SalaryLv1 = 100,
	SalaryMaxLv = 4100,
	LegacyNotes = "Doug Milton originates from Kentucky. He quit school in the fourth grade to work in his father's gas station. When his sister/cousin started pumping gas at the garage, he transferred his focus to the repair bench, and became a good mechanic. Since he left the family business, he roamed from job to job before trying his luck as a mercenary.\" - M.E.R.C. Dossier",
	MaxHitPoints = 82,
	Likes = {
		"Vicki",
	},
	Dislikes = {
		"Ivan",
		"Igor",
	},
	StartingPerks = {
		"Gasket",
		"MrFixit",
	},
	AppearancesList = {
		PlaceObj('AppearanceWeight', {
			'Preset', "Gasket-Appearance",
		}),
	},
	Equipment = {
		"Wolf",
	},
	Specialization = "Mechanic",
	gender = "Male",
	blocked_spots = set( "Weaponls", "Weaponrs" ),
}

