UndefineClass('GCExGumpy')
DefineClass.GCExGumpy = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",


	NameColor = 4292643868,
	object_class = "UnitData",
	Health = 67,
	Agility = 45,
	Dexterity = 67,
	Strength = 70,
	Wisdom = 94,
	Leadership = 11,
	Marksmanship = 44,
	Mechanical = 0,
	Explosives = 56,
	Medical = 9,
	Portrait = "Mod/GCExPrologue/Images/GumpyPortrait",
	BigPortrait = "Mod/GCExPrologue/Images/IMG_8537 2",
	IsMercenary = true,
	Name = T(350774746706, --[[ModItemUnitDataCompositeDef GCExGumpy Name]] 'Tim "Gumpy" Hillman'),
	Nick = T(940139436494, --[[ModItemUnitDataCompositeDef GCExGumpy Nick]] "Gumpy"),
	AllCapsNick = T(284042248626, --[[ModItemUnitDataCompositeDef GCExGumpy AllCapsNick]] "GUMPY"),
	Affiliation = "Secret",
	Bio = T(845088535160, --[[ModItemUnitDataCompositeDef GCExGumpy Bio]] "Tim is a brilliant explosives expert who catches on quickly. When it comes to explosives though, there really isn't much room for error. Tim Hillman would probably still be enrolled in Harvard, doing graduate studies in electro-magnetic research, if it wasn't for a couple bouts of severe depression...possibly due to the constant exposure to EMF.\n\nAdditional Info:\n\nDue to acute allergies, Tim prefers to work in northern climates.\n\n- M.E.R.C. Dossier"),
	Nationality = "USA",
	snype_nick = T(140402586340, --[[ModItemUnitDataCompositeDef GCExGumpy snype_nick]] "tim.hilman"),
	Refusals = {},
	Haggles = {},
	Mitigations = {},
	ExtraPartingWords = {},
	Offline = {},
	GreetingAndOffer = {},
	ConversationRestart = {},
	IdleLine = {},
	PartingWords = {},
	RehireIntro = {},
	RehireOutro = {},
	MedicalDeposit = "none",
	StartingSalary = 470,
	SalaryIncrease = 280,
	SalaryLv1 = 100,
	SalaryMaxLv = 4100,
	LegacyNotes = '"Tim is a brilliant explosives expert who catches on quickly. When it comes to explosives though, there really isn\'t much room for error. Tim Hillman would probably still be enrolled in Harvard, doing graduate studies in electro-magnetic research, if it wasn\'t for a couple bouts of severe depression...possibly due to the constant exposure to EMF.\n\nAdditional Info:\n\nDue to acute allergies, Tim prefers to work in northern climates."\n\n- M.E.R.C. Dossier',
	MaxHitPoints = 82,
	StartingPerks = {
		"GumpySpecialPineapple",
		"MrFixit",
	},
	AppearancesList = {
		PlaceObj('AppearanceWeight', {
			'Preset', "Gumpy-Appearance",
		}),
	},
	Equipment = {
		"Red",
	},
	Specialization = "ExplosiveExpert",
	gender = "Male",
	blocked_spots = set( "Weaponls", "Weaponrs" ),
}

