UndefineClass('GCExCougar')
DefineClass.GCExCougar = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",


	NameColor = 4292643868,
	object_class = "UnitData",
	Health = 88,
	Agility = 83,
	Dexterity = 79,
	Strength = 87,
	Wisdom = 75,
	Leadership = 31,
	Marksmanship = 93,
	Mechanical = 58,
	Explosives = 45,
	Medical = 33,
	Portrait = "Mod/GCExPrologue/Images/CougarPortrait",
	BigPortrait = "Mod/GCExPrologue/Images/Cougar",
	IsMercenary = true,
	Name = T(823708430215, --[[ModItemUnitDataCompositeDef GCExCougar Name]] 'Jim "Cougar" Wallace'),
	Nick = T(346183843645, --[[ModItemUnitDataCompositeDef GCExCougar Nick]] "Cougar"),
	AllCapsNick = T(245400817655, --[[ModItemUnitDataCompositeDef GCExCougar AllCapsNick]] "COUGAR"),
	Affiliation = "Secret",
	Bio = T(549374649264, --[[ModItemUnitDataCompositeDef GCExCougar Bio]] "Jim Wallace is one of the few cadets ever to get a perfect score on every final exam at military college. Of course, it didn't hurt that his father wrote the school's military code of conduct. He's a master at conventional mercenary skills and a pro with automatic weaponry. Always by-the-book Cougar is highly professional, possibly M.E.R.C's top performer.\" - M.E.R.C. Dossier\n\nAdditional Info\n\"Even though he is a man with strong opinions, Cougar has the military background (and discipline) to keep them to himself.\""),
	Nationality = "USA",
	snype_nick = T(737933631206, --[[ModItemUnitDataCompositeDef GCExCougar snype_nick]] "jim.wallace"),
	Refusals = {},
	Haggles = {},
	Mitigations = {},
	ExtraPartingWords = {},
	Offline = {},
	GreetingAndOffer = {},
	ConversationRestart = {},
	IdleLine = {},
	PartingWords = {},
	RehireIntro = {},
	RehireOutro = {},
	MedicalDeposit = "none",
	StartingSalary = 470,
	SalaryIncrease = 280,
	SalaryLv1 = 100,
	SalaryMaxLv = 4100,
	LegacyNotes = '"Jim Wallace is one of the few cadets ever to get a perfect score on every final exam at military college. Of course, it didn\'t hurt that his father wrote the school\'s military code of conduct. He\'s a master at conventional mercenary skills and a pro with automatic weaponry. Always by-the-book Cougar is highly professional, possibly M.E.R.C\'s top performer." - M.E.R.C. Dossier\n\nAdditional Info\n"Even though he is a man with strong opinions, Cougar has the military background (and discipline) to keep them to himself."',
	StartingLevel = 5,
	MaxHitPoints = 82,
	Likes = {
		"Len",
		"Wolf",
	},
	StartingPerks = {
		"ByTheBook",
		"AutoWeapons",
		"Stealthy",
		"Deadeye",
		"Flanker",
		"LightningReaction",
		"RelentlessAdvance",
	},
	AppearancesList = {
		PlaceObj('AppearanceWeight', {
			'Preset', "Cougar-Appearance",
		}),
	},
	Equipment = {
		"Len",
	},
	Tier = "Elite",
	Specialization = "Marksmen",
	gender = "Male",
	blocked_spots = set( "Weaponls", "Weaponrs" ),
	VoiceResponseId = "GCExCougar",
}

