UndefineClass('GCExNumb')
DefineClass.GCExNumb = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",


	NameColor = 4292643868,
	object_class = "UnitData",
	Health = 84,
	Agility = 73,
	Dexterity = 62,
	Strength = 78,
	Wisdom = 70,
	Leadership = 13,
	Marksmanship = 88,
	Mechanical = 14,
	Explosives = 22,
	Medical = 33,
	Portrait = "Mod/GCExPrologue/Images/NumbPortrait",
	BigPortrait = "Mod/GCExPrologue/Images/Numb",
	IsMercenary = true,
	Name = T(561852629506, --[[ModItemUnitDataCompositeDef GCExNumb Name]] 'Tim "Numb" Sutton'),
	Nick = T(392128018814, --[[ModItemUnitDataCompositeDef GCExNumb Nick]] "Numb"),
	AllCapsNick = T(531854446711, --[[ModItemUnitDataCompositeDef GCExNumb AllCapsNick]] "NUMB"),
	Affiliation = "Secret",
	Bio = T(792089849295, --[[ModItemUnitDataCompositeDef GCExNumb Bio]] "Tim Sutton suffers from a bad case of visual offensiveness and no one has been willing to give him a break. His bad haircut and neck tattoo has hindered this mercenary's career pursuits despite an otherwise impressive resume including martial arts and night ops training. His marksmanship and medical abilities are also excellent."),
	Nationality = "England",
	snype_nick = T(859662584234, --[[ModItemUnitDataCompositeDef GCExNumb snype_nick]] "tim.sutton"),
	Refusals = {},
	Haggles = {},
	Mitigations = {},
	ExtraPartingWords = {},
	Offline = {},
	GreetingAndOffer = {},
	ConversationRestart = {},
	IdleLine = {},
	PartingWords = {},
	RehireIntro = {},
	RehireOutro = {},
	MedicalDeposit = "none",
	StartingSalary = 470,
	SalaryIncrease = 280,
	SalaryLv1 = 100,
	SalaryMaxLv = 4100,
	LegacyNotes = '"Tim Sutton suffers from a bad case of visual offensiveness and no one has been willing to give him a break. His bad haircut and neck tattoo has hindered this mercenary\'s career pursuits despite an otherwise impressive resume including martial arts and night ops training. His marksmanship and medical abilities are also excellent." - M.E.R.C. dossier',
	StartingLevel = 3,
	MaxHitPoints = 82,
	Dislikes = {
		"Vicki",
		"Sidney",
		"Scope",
	},
	StartingPerks = {
		"NumbTalk",
		"MartialArts",
		"NightOps",
		"Flanker",
		"BreachAndClear",
	},
	AppearancesList = {
		PlaceObj('AppearanceWeight', {
			'Preset', "Numb-Appearance",
		}),
	},
	Equipment = {
		"Sidney",
	},
	Tier = "Veteran",
	Specialization = "Marksmen",
	gender = "Male",
	blocked_spots = set( "Weaponls", "Weaponrs" ),
}

