UndefineClass('GCExGaston')
DefineClass.GCExGaston = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",


	NameColor = 4292643868,
	object_class = "UnitData",
	Health = 88,
	Agility = 82,
	Dexterity = 96,
	Strength = 84,
	Wisdom = 80,
	Leadership = 28,
	Marksmanship = 94,
	Mechanical = 22,
	Explosives = 21,
	Medical = 23,
	Portrait = "Mod/GCExPrologue/Images/GastonPortrait",
	BigPortrait = "Mod/GCExPrologue/Images/Gaston",
	IsMercenary = true,
	Name = T(833359843240, --[[ModItemUnitDataCompositeDef GCExGaston Name]] "Gaston Cavalier"),
	Nick = T(513999821212, --[[ModItemUnitDataCompositeDef GCExGaston Nick]] "Gaston"),
	AllCapsNick = T(849984528283, --[[ModItemUnitDataCompositeDef GCExGaston AllCapsNick]] "GASTON"),
	Affiliation = "Secret",
	Bio = T(321537150794, --[[ModItemUnitDataCompositeDef GCExGaston Bio]] "As a distinguished commando in the French Marine Corp (FMC), Gaston has played a distinguished role in many of the NATO and UN operations throughout this hostile world. A confident, field-proven, professional sharpshooter, Cavalier's addition to our roster is just another step in M.E.R.C.'s continuing effort to meet your needs.\n\nAdditional Info\n\nGaston operates best in the early hours of the morning. He is also rather apt at sniping from an elevated vantage point.\n\n-M.E.R.C. Dossier"),
	Nationality = "France",
	snype_nick = T(189826039300, --[[ModItemUnitDataCompositeDef GCExGaston snype_nick]] "gaston.cavalier"),
	Refusals = {},
	Haggles = {},
	Mitigations = {},
	ExtraPartingWords = {},
	Offline = {},
	GreetingAndOffer = {},
	ConversationRestart = {},
	IdleLine = {},
	PartingWords = {},
	RehireIntro = {},
	RehireOutro = {},
	MedicalDeposit = "none",
	StartingSalary = 470,
	SalaryIncrease = 280,
	SalaryLv1 = 100,
	SalaryMaxLv = 4100,
	LegacyNotes = '"As a distinguished commando in the French Marine Corp (FMC), Gaston has played a distinguished role in many of the NATO and UN operations throughout this hostile world. A confident, field-proven, professional sharpshooter, Cavalier\'s addition to our roster is just another step in M.E.R.C.\'s continuing effort to meet your needs.\n\nAdditional Info\n\nGaston operates best in the early hours of the morning. He is also rather apt at sniping from an elevated vantage point."\n\n-M.E.R.C. Dossier',
	StartingLevel = 6,
	MaxHitPoints = 82,
	Likes = {
		"Fox",
	},
	LearnToLike = {
		"Buns",
	},
	StartingPerks = {
		"Gaston",
		"NightOps",
		"DeathFromAbove",
		"Deadeye",
		"Counterfire",
		"Hotblood",
		"Killzone",
	},
	AppearancesList = {
		PlaceObj('AppearanceWeight', {
			'Preset', "Gaston-Appearance",
		}),
	},
	Equipment = {
		"Scope",
	},
	Tier = "Elite",
	Specialization = "Marksmen",
	gender = "Male",
	blocked_spots = set( "Weaponls", "Weaponrs" ),
}

