UndefineClass('GCExFlo')
DefineClass.GCExFlo = {
	__parents = { "UnitData" },
	__generated_by_class = "ModItemUnitDataCompositeDef",


	NameColor = 4282219161,
	object_class = "UnitData",
	Health = 58,
	Agility = 37,
	Dexterity = 64,
	Strength = 45,
	Wisdom = 82,
	Leadership = 1,
	Marksmanship = 38,
	Mechanical = 7,
	Explosives = 2,
	Medical = 19,
	Portrait = "Mod/GCExPrologue/Images/FloPortrait",
	BigPortrait = "Mod/GCExPrologue/Images/Flo",
	Name = T(183982423479, --[[ModItemUnitDataCompositeDef GCExFlo Name]] 'Florence "Flo" Gabriel'),
	Nick = T(445040565694, --[[ModItemUnitDataCompositeDef GCExFlo Nick]] "Flo"),
	AllCapsNick = T(572992729569, --[[ModItemUnitDataCompositeDef GCExFlo AllCapsNick]] "FLO"),
	Affiliation = "Other",
	Bio = T(234573707265, --[[ModItemUnitDataCompositeDef GCExFlo Bio]] "The daughter of vineyard workers, Florence Gabriel spent most of her childhood in Cognac, France before moving to Pittsburgh, Pennsylvania, USA. After settling in the US she took a job as the bookkeeper for a major gun dealer, where she acquired extensive knowledge on the value of firearms. Slightly hesitant, but bright, Flo is simply priced too low to pass up."),
	Nationality = "France",
	snype_nick = T(965203635079, --[[ModItemUnitDataCompositeDef GCExFlo snype_nick]] "florence.gabriel"),
	Refusals = {},
	Haggles = {},
	Mitigations = {},
	ExtraPartingWords = {},
	Offline = {},
	GreetingAndOffer = {},
	ConversationRestart = {},
	IdleLine = {},
	PartingWords = {},
	RehireIntro = {},
	RehireOutro = {},
	MedicalDeposit = "none",
	StartingSalary = 470,
	SalaryIncrease = 280,
	SalaryLv1 = 100,
	SalaryMaxLv = 4100,
	LegacyNotes = "The daughter of vineyard workers, Florence Gabriel spent most of her childhood in Cognac, France before moving to Pittsburgh, Pennsylvania, USA. After settling in the US she took a job as the bookkeeper for a major gun dealer, where she acquired extensive knowledge on the value of firearms. Slightly hesitant, but bright, Flo is simply priced too low to pass up.",
	immortal = true,
	MaxHitPoints = 82,
	Dislikes = {
		"Meltdown",
	},
	AppearancesList = {
		PlaceObj('AppearanceWeight', {
			'Preset', "Flo-Appearance",
		}),
	},
	Specialization = "AllRounder",
	gender = "Female",
	blocked_spots = set( "Weaponls", "Weaponrs" ),
	PersistentSessionId = "GCEXFlo",
}

